# Generated by Django 4.0.6 on 2022-07-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0006_rename_theauthors_theauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Book name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image book')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price book (byn)')),
                ('the_year_of_publishing', models.IntegerField(blank=True, null=True, verbose_name='The year of publishing')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Pages')),
                ('binding', models.CharField(blank=True, max_length=30, null=True, verbose_name='Binding')),
                ('format', models.CharField(blank=True, max_length=30, null=True, verbose_name='Format')),
                ('isbn', models.IntegerField(blank=True, null=True, verbose_name='ISBN')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight (gram)')),
                ('Age_restrictions', models.IntegerField(blank=True, null=True, verbose_name='Age restrictions')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('active', models.CharField(blank=True, max_length=10, null=True, verbose_name='Are available (yes/no)')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('data_register', models.DateField(blank=True, null=True, verbose_name='Date of entry into the catalog')),
                ('data_changes', models.DateField(blank=True, null=True, verbose_name='Date of the last change of the card')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalogue.theauthor', verbose_name='Author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalogue.genre', verbose_name='Genre')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalogue.publishinghouse', verbose_name='PublishingHouse')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalogue.series', verbose_name='Series')),
            ],
        ),
    ]
