# Generated by Django 4.0.6 on 2022-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_product', '0002_remove_book_author_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are available (yes/no)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='data_changes',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date of the last change of the card'),
        ),
        migrations.AlterField(
            model_name='book',
            name='data_register',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of entry into the catalog'),
        ),
    ]
