# Generated by Django 4.0.6 on 2022-07-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_product', '0006_alter_book_data_changes_alter_book_data_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Age_restrictions',
            new_name='age_restrictions',
        ),
    ]
