# Generated by Django 4.0.6 on 2022-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_product', '0007_rename_age_restrictions_book_age_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Book name'),
        ),
    ]
