# Generated by Django 4.0.6 on 2022-07-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='The_authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
            ],
        ),
    ]
