# Generated by Django 4.0.6 on 2022-07-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_publishing_house'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publishing_house',
            new_name='PublishingHouse',
        ),
        migrations.RenameModel(
            old_name='The_authors',
            new_name='TheAuthors',
        ),
    ]
