# Generated by Django 4.0.6 on 2022-07-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_rename_publishing_house_publishinghouse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheAuthors',
            new_name='TheAuthor',
        ),
    ]
