# Generated by Django 4.0.6 on 2022-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_rename_theauthors_theauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Status')),
            ],
        ),
    ]
