# Generated by Django 4.0.6 on 2022-08-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_product', '0010_alter_book_price'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, verbose_name='Created')),
                ('quantity', models.SmallIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='card_product.book', verbose_name='Book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
