# Generated by Django 4.0.6 on 2022-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_updated_date_bookincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
