# Generated by Django 4.0.6 on 2022-08-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_additional_information_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='delivery_addres',
        ),
    ]
