# Generated by Django 4.0.6 on 2022-08-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_status'),
        ('orders', '0007_rename_delivery_addres_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogue.status', verbose_name='Status'),
        ),
    ]
